### ISSUE TITLE
Wisps crash during December and sometimes on the 31st of the month.

### ISSUE THREAD

**Issue by wenlfs** [JarHax/SpookyJam2018#2]
Hi!
I'm have this crash that happens pointing an entity of yours.

https://pastebin.com/tpzBUuyT

Thank you.

**Comment by Sunconure11** [comment]
User ran into the same error, but it fired when looking at a TC Wisp. WTF?

https://paste.dimdev.org/wevusolume.mccrash

@darkhax

**Comment by Darkhax** [comment]
Thanks for the report, I meant to push a fix out sooner but got a bit side tracked. This crash is actually related to the will-o'-wisp added by this mod, and not the Thaumcraft wisp. A fix will be out very soon.

**Comment by Darkhax** [comment]
A new release has been pushed to CurseForge which has the fix to this issue. https://minecraft.curseforge.com/projects/eerie-entities/files/2644961
